general {
    # Comando para bloquear la pantalla. Usa 'pidof' para evitar que se inicien múltiples
    # instancias de hyprlock si ya está corriendo.
    lock_cmd = pidof hyprlock || hyprlock

    # Comando que se ejecuta justo antes de que el sistema se suspenda.
    # 'loginctl lock-session' asegura que la sesión se bloquee antes de dormir.
    before_sleep_cmd = loginctl lock-session

    # Comando que se ejecuta al reanudar el sistema del modo de suspensión.
    # 'dpms on' enciende la pantalla, útil para evitar pantallas negras al despertar.
    after_sleep_cmd = hyprctl dispatch dpms on
}

# --- Oyentes de inactividad (Listeners) ---
# Cada 'listener' ejecuta una acción específica después de un tiempo de inactividad.

# Bloqueo de pantalla después de 10 minutos
listener {
    # 'timeout' en segundos. 600 segundos = 10 minutos.
    timeout = 600
    # Comando a ejecutar cuando se alcanza el tiempo de espera.
    on-timeout = hyprlock
}

# Apagado del monitor después de 15 minutos
listener {
    # 900 segundos = 15 minutos.
    timeout = 900
    # Apaga la pantalla (Display Power Management Signaling).
    on-timeout = hyprctl dispatch dpms off
    # Enciende la pantalla al detectar actividad de nuevo.
    on-resume = hyprctl dispatch dpms on
}

# Suspensión del sistema después de 16 minutos
listener {
    # 960 segundos = 16 minutos.
    timeout = 960 
    # Comando para suspender el sistema (ponerlo a dormir).
    on-timeout = systemctl suspend
}
