set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux#v2.1.3'

# Anula la tecla de prefijo por defecto de tmux (Ctrl+b)
unbind C-b

# Establece la nueva tecla de prefijo a Ctrl+g
set-option -g prefix C-g

# Re-enlaza el atajo para enviar el prefijo al terminal para que funcione con la nueva tecla
bind-key C-g send-prefix

# Estable nueva tecla para ventana flotante
bind-key -n M-f if-shell -F '#{==:#{session_name},scratch}' {
detach-client
} {
# open in the same directory of the current pane
display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

set -g mouse on
set -g status-position top
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

set -g default-terminal "tmux-256color"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run '~/.tmux/plugins/tpm/tpm'
