set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'

#theme
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-plugins "git cpu-usage ram-usage"
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-show-battery false
set -g @kanagawa-show-powerline true
set -g @kanagawa-refresh-rate 10

# Anula la tecla de prefijo por defecto de tmux (Ctrl+b)
unbind C-b

# Establece la nueva tecla de prefijo a Ctrl+g
set-option -g prefix C-g

# Re-enlaza el atajo para enviar el prefijo al terminal para que funcione con la nueva tecla
bind-key C-g send-prefix

# Estable nueva tecla para ventana flotante
bind-key -n M-f if-shell -F '#{==:#{session_name},scratch}' {
detach-client
} {
# open in the same directory of the current pane
display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# easy reload config
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

set -g mouse on
set -g status-position top
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# Fix colors for the terminal
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ",xterm-256color:Tc"

#mode vim
set -g mode-keys vi
if-shell 'uname | grep -q Darwin' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

set -g base-index 1
setw -g pane-base-index 1

run '~/.tmux/plugins/tpm/tpm'
